version: "3.8"
services:
  db:
    image: postgres:15
    restart: always
    environment:
    POSTGRES_DB: smart_hack
    POSTGRES_USER: fastuser
    POSTGRES_PASSWORD: fastpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
pgdata: